/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDefault: typeof import('./components/alerts/AlertDefault.vue')['default']
    BaseDataTable: typeof import('./components/tables/BaseDataTable.vue')['default']
    CardConfirmDelete: typeof import('./components/cards/CardConfirmDelete.vue')['default']
    DialogAddToCart: typeof import('./components/dialogs/DialogAddToCart.vue')['default']
    DialogConfirmDelete: typeof import('./components/dialogs/DialogConfirmDelete.vue')['default']
    Loading: typeof import('./components/load/Loading.vue')['default']
    MenuFilterSelect: typeof import('./components/filters/MenuFilterSelect.vue')['default']
    MenuFilterTextField: typeof import('./components/filters/MenuFilterTextField.vue')['default']
    PageHeader: typeof import('./components/cards/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/text-fields/SearchBar.vue')['default']
    TemporaryCard: typeof import('./components/cards/TemporaryCard.vue')['default']
    VerificationCodeInputCard: typeof import('./components/cards/VerificationCodeInputCard.vue')['default']
  }
}
